-- Retreiving Identity Column values 

/*
In this session we will learn 

 -->How to get the last generated identity column value 

 -->Difference between SCOPE_IDENTITY(), @@iDENTITY and 
 IDENT_CURRENT('TableName')

 


 Retreiving Identity Column values 

 Pre Req - Part 7 - Identity Column in SQL Server

 From the previous session, we understood that identity column values are auto generated. There are several ways in sql server, to retreive the last identity value that is generated. The most common wyas is to use SCOPE_IDENTITY()  built in function.

 Difference:
 SCOPE_IDENTITY() - Same session and the same scope.
 @@IDENTITY - Same session and across any scope.
 IDENT_CURRENT('TableName') - Specific table across any session and any scope.

 */

 CREATE DATABASE Part8Sample;

 USE [Part8Sample]
 GO

 CREATE TABLE Test1
 (
 ID INT IDENTITY(1,1),
 Value NVARCHAR(20)
 );

 CREATE TABLE Test2
 (
 ID INT IDENTITY(1,1),
 Value NVARCHAR(20)
 );

 INSERT INTO Test2 VALUES('zzz')

 SELECT SCOPE_IDENTITY()
 SELECT @@iDENTITY 
 SELECT IDENT_CURRENT('Test2')

 INSERT INTO Test1 VALUES ('X')

 SELECT * FROM Test1;
  SELECT * FROM Test2;

 CREATE TRIGGER trForInsert ON Test1 FOR INSERT
 AS
 BEGIN
   INSERT INTO test2 VALUES ('YYYY')
 END

 SELECT SCOPE_IDENTITY()
 SELECT @@IDENTITY 


 /*
 # Part 8 – Retrieving Identity Column Values (Interview Questions)

## Basic Questions

1. What is `SCOPE_IDENTITY()`?
2. Why do we use `SCOPE_IDENTITY()`?
3. What is `@@IDENTITY`?
4. Why do we use `@@IDENTITY`?
5. What is `IDENT_CURRENT('TableName')`?
6. Why do we use `IDENT_CURRENT('TableName')`?
7. What is the purpose of retrieving the last generated Identity value?

## Concept Questions

8. What is the difference between `SCOPE_IDENTITY()`, `@@IDENTITY`, and `IDENT_CURRENT()`?
9. What does **Scope** mean in SQL Server?
10. What does **Session** mean in SQL Server?
11. Which function returns the last Identity value generated in the same scope and same session?
12. Which function returns the last Identity value generated in the same session across all scopes?
13. Which function returns the last Identity value generated for a specific table across all sessions?
14. Which function is recommended after inserting a record? Why?
15. Which function is considered the safest for retrieving the last inserted Identity value?

## Trigger-Based Questions

16. How does a Trigger affect `@@IDENTITY`?
17. Why does `@@IDENTITY` return a different value when a Trigger inserts into another table?
18. Why is `SCOPE_IDENTITY()` not affected by a Trigger?
19. In the given example, why is a row inserted into `Test2` when inserting into `Test1`?
20. Which function should you use if your table has Triggers?

## Practical Questions

21. Write a query to retrieve the last Identity value using `SCOPE_IDENTITY()`.
22. Write a query to retrieve the last Identity value using `@@IDENTITY`.
23. Write a query to retrieve the last Identity value of a specific table using `IDENT_CURRENT()`.
24. Create a Trigger that inserts a record into another table.
25. Demonstrate the difference between `SCOPE_IDENTITY()` and `@@IDENTITY` using a Trigger.

## Scenario-Based Questions

26. What happens if another user inserts a record into the same table while you are using `IDENT_CURRENT()`?
27. Can `IDENT_CURRENT()` return a value generated by another session?
28. Why is `IDENT_CURRENT()` not suitable for retrieving the last inserted record of the current user?
29. Which function would you use in a multi-user application? Why?
30. Which function would you use after inserting a new customer record in an online banking application?

## Comparison Questions

31. What is the difference between **Scope** and **Session**?
32. What is the difference between `SCOPE_IDENTITY()` and `@@IDENTITY`?
33. What is the difference between `@@IDENTITY` and `IDENT_CURRENT()`?
34. What is the difference between `SCOPE_IDENTITY()` and `IDENT_CURRENT()`?
35. Which function is the most reliable for retrieving the last inserted Identity value? Explain.

## Real-World Questions

36. Where are `SCOPE_IDENTITY()`, `@@IDENTITY`, and `IDENT_CURRENT()` used in real-world applications?
37. What are the advantages of using `SCOPE_IDENTITY()`?
38. What are the limitations of `@@IDENTITY`?
39. Why do most developers prefer `SCOPE_IDENTITY()` over `@@IDENTITY`?
40. Give a real-world example where using `@@IDENTITY` can produce incorrect results.

# ⭐ Most Important Questions (Freshers)

1. What is `SCOPE_IDENTITY()`?
2. What is `@@IDENTITY`?
3. What is `IDENT_CURRENT('TableName')`?
4. What is the difference between `SCOPE_IDENTITY()`, `@@IDENTITY`, and `IDENT_CURRENT()`?
5. What is the difference between **Scope** and **Session**?
6. Which function is safest for retrieving the last inserted Identity value? Why?
7. How does a Trigger affect `@@IDENTITY`?
8. Why is `SCOPE_IDENTITY()` preferred over `@@IDENTITY`?
9. Can `IDENT_CURRENT()` return a value generated by another user/session?
10. Write SQL queries using `SCOPE_IDENTITY()`, `@@IDENTITY`, and `IDENT_CURRENT()`.
*/