-- What is Identity?
-- Creating an Identity column
-- Supply explicit values for identity columns using IDENTITY_INSERT
-- Reset identity value using DBCC CHECKIDENT command

CREATE DATABASE Part7Sample;

USE Part7Sample;
GO

CREATE TABLE tblPerson
(
ID INT PRIMARY KEY,
Name NVARCHAR(50),
Email NVARCHAR(50),
GenderID INT,
Age INT
);

CREATE TABLE tblGender
(
ID INT PRIMARY KEY,
Gender NVARCHAR(50) 
);

INSERT INTO tblGender VALUES
(1, 'Male'),
(2, 'Female'),
(3, 'Unknown'); 



INSERT INTO tblPerson VALUES 
(1, 'John', 'j@j.com', NULL, NULL),
(2, 'Ron', 'mr.com', 1, NULL),
(3, 'Rich', 'r@r.com', NULL, NULL),
(4, 'Sara', 's@r.com', 2, 10),
(5, 'Sara', 's@s.com', 2,NULL),
(6, 'Jane', 'a@a.com', 2, NULL);

UPDATE tblPerson
SET 
Name = 'Jane',
Email = 'a@a.com',
GenderID = '1',
Age = 20
WHERE ID = 6;


INSERT INTO tblPerson VALUES 
(7, 'Todd', 't@t.com', 1, 25);

SELECT * FROM tblGender 
SELECT * FROM tblPerson 

SELECT * FROM tblPerson1; 

INSERT INTO tblPerson1 VALUES ( 'Martin');

DELETE FROM tblPerson1 WHERE PersonId = 1;

SET IDENTITY_INSERT tblPerson1 OFF 

INSERT INTO tblPerson1 (PersonId, Name) VALUES (1, 'Jane');

An explicit value for the identity column in table tblPerson1
can only be specified when a column list is used and IDENTITY_INSERT is ON.

/*
If a column is marked as an identity column, then the values for this column are automatically generated, when you insert a new into the table.

CREATE TABLE tblPerson
(
PersonId INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(20)
)

Note: Seed and Increment values are optional. If you don't specify the Identity and seed they both default to 1.
To explicit supply a value for identity column
1. First turn on identity insert-SET Identity_Insert tblPerson ON
2. In the insert query specify the column list
    Insert into tblPerson(PersonId, Name) VALUES (2, 'John')

    If you have deleted all the rows in a table, and you want to reset the identity column value, use DBCC CHECKIDENT command.

    DBCC CHECKIDENT('tblPerson', RESEED, 0)


*/


DELETE FROM tblPerson1; 

DBCC CHECKIDENT(tblPerson1, reseed, 0);

SELECT * FROM tblPerson1; 

/*
# Part 7 – Identity Column (Interview Questions)

## Basic Questions

1. What is an Identity Column in SQL Server?
2. Why do we use an Identity Column?
3. What is the purpose of an Identity Column?
4. What is the syntax for creating an Identity Column?
5. What do the Seed and Increment values mean?
6. What are the default Seed and Increment values if they are not specified?
7. Can a table have more than one Identity Column?

## Concept Questions

8. How does an Identity Column work internally?
9. Does SQL Server automatically generate values for an Identity Column?
10. Can duplicate values be generated by an Identity Column?
11. Can an Identity Column contain NULL values?
12. Does deleting a row reset the Identity value?
13. Does truncating a table reset the Identity value?
14. What happens if the SQL Server service is restarted? Does the Identity value reset?
15. Can an Identity Column guarantee gap-free values?

## Practical Questions

16. How do you create a table with an Identity Column?
17. How do you insert data into a table with an Identity Column?
18. How do you insert an explicit value into an Identity Column?
19. Why must `IDENTITY_INSERT` be set to `ON` before inserting explicit values?
20. Why must you specify the column list when using `IDENTITY_INSERT`?
21. Can `IDENTITY_INSERT` be enabled for multiple tables at the same time?
22. How do you turn `IDENTITY_INSERT` ON and OFF?
23. What happens if you try to insert an explicit Identity value while `IDENTITY_INSERT` is OFF?

## DBCC CHECKIDENT Questions

24. What is the `DBCC CHECKIDENT` command?
25. Why do we use `DBCC CHECKIDENT`?
26. What does the `RESEED` option do?
27. How do you reset the Identity value using `DBCC CHECKIDENT`?
28. When should you reset an Identity Column?
29. What happens after reseeding the Identity value to 0?

## Scenario-Based Questions

30. What happens if you delete all rows from a table with an Identity Column?
31. What happens if you insert a new record after deleting all rows?
32. What happens if you reseed the Identity value lower than the current maximum value?
33. What happens if you insert a duplicate explicit Identity value?
34. Can Identity values be updated manually?

## Comparison Questions

35. What is the difference between a Primary Key and an Identity Column?
36. Can a Primary Key exist without an Identity Column?
37. Can an Identity Column exist without being a Primary Key?
38. What is the difference between `DELETE`, `TRUNCATE`, and `DBCC CHECKIDENT` with respect to Identity values?

## Real-World Questions

39. Where are Identity Columns used in real-world applications?
40. What are the advantages of using Identity Columns?
41. What are the limitations of Identity Columns?
42. Give a real-world example where an Identity Column is useful.

# ⭐ Most Important Questions (Freshers)

1. What is an Identity Column?
2. Why do we use an Identity Column?
3. What is the syntax of an Identity Column?
4. What do Seed and Increment values mean?
5. What are the default Seed and Increment values?
6. What is `IDENTITY_INSERT` and why do we use it?
7. Why must the column list be specified when using `IDENTITY_INSERT`?
8. What is `DBCC CHECKIDENT`?
9. How do you reset an Identity value?
10. What is the difference between a Primary Key and an Identity Column?
*/
